### ISSUE TITLE
Missing Information

### ISSUE THREAD

**Issue by hammadsaedi** [farehiqbal/farehiqbal#1]
Your Git stats show more Java than Python but you mention only pyhton. Mr. Muhammad Mustafa Khatak will not let you go. Lag pta jae ga. Loving Umar Iqbal? 😏

**Comment by farehiqbal** [comment]
Baaz aa

**Comment by farehiqbal** [comment]
Java da icon ni c lab rya

**Comment by hammadsaedi** [comment]
Google kr na 😏

**Comment by farehiqbal** [comment]
O yar wo png ni lag ra na isliye, me kya charho mere…

**Comment by hammadsaedi** [comment]
### Add this shit!
```
<a href="https://www.java.com" target="_blank" rel="noreferrer"> <img src="https://uploads-ssl.webflow.com/5ffe5bee629c3505f14fb1fd/604aa487faeeda20e43980d2_java_logo.png" alt="java" width="40" height="40"/> </a>  
</p>
```
### Make Change!
<a href="https://www.java.com" target="_blank" rel="noreferrer"> <img src="https://uploads-ssl.webflow.com/5ffe5bee629c3505f14fb1fd/604aa487faeeda20e43980d2_java_logo.png" alt="java" width="40" height="40"/> </a>  
</p>

**Comment by farehiqbal** [comment]
Thank you!
